name: Docker Image CI/CD for Staging

on:
  push:
    branches: ["production"]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}

      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ env.DOCKER_USERNAME }}/cloudybd-server:${GITHUB_REF##*/}

      - name: Docker Push
        run: docker push ${{ env.DOCKER_USERNAME }}/cloudybd-server:${GITHUB_REF##*/}

      - name: Tag Docker image with version
        run: docker tag  ${{ env.DOCKER_USERNAME }}/cloudybd-server:${GITHUB_REF##*/} ${{ env.DOCKER_USERNAME }}/cloudybd-server:$(jq -r '.version' package.json)

      - name: Docker Push version
        run: docker push ${{ env.DOCKER_USERNAME }}/cloudybd-server:$(jq -r '.version' package.json)
  discord:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test Success
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          username: Cloudy BD API - Production
          details: "The deployment was successful without any issues."
          webhookUrl: ${{ env.DISCORD_WEBHOOK }}
      - name: Test Failure
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          username: Cloudy BD API - Production
          details: Test Failed!
          webhookUrl: ${{ env.DISCORD_WEBHOOK }}
      - name: Test Cancelled
        uses: rjstone/discord-webhook-notify@v1
        if: cancelled()
        with:
          severity: warn
          username: Cloudy BD API - Production
          details: Test Cancelled!
          webhookUrl: ${{ env.DISCORD_WEBHOOK }}